### ISSUE TITLE
How to enable mpx or prefix mode?

### ISSUE THREAD

**Issue by lbxl2345** [HexHive/datashield#3]
I follow the steps in readme, and the helloworld test works fine. But when I modify the scripts in /datashield/bin and enable MPX, it doesn't insert any check code into the executable. Any tips?

**Comment by scottcarr** [comment]
Can you post your script?

Note that you need both `-datashield-use-late-mpx` and `-datashield-use-prefix-check` IIRC.

**Comment by lbxl2345** [comment]
I correct the order of these two options and it works now, thx!
Besides, there's a mistake in readme, in section **Compiling Instrumented Programs**, the PATH should be $HOME/research/datashield/bin.

**Comment by scottcarr** [comment]
I've updated README.md.  Thanks.
