### ISSUE TITLE
abort when running binary

### ISSUE THREAD

**Issue by boofish** [HexHive/datashield#5]
Hello,
I am succeeded in compiling the compiler and handwritten binaries by following the steps in the readme.
However, 
when I run the binaries, it reports an `Aborted` message,
and it shows the information.
```
[DC Runtime]unsafe heap top: 0xff7fd000
mapping failed!
Assertion failed: : 0 (../musl/src/datashield/datashield.c: __ds_init: 488)
Aborted
```
Any ideas?

**Comment by gannimo** [comment]
This code is ~4 years old and was only tested on systems from that time. Can you clarify what Ubuntu version (16.04 should work), llvm, and musl versions you are using?

Looking at the assertion error, it seems that musl is unable to map a region of memory and it looks as if it's 32-bit (and not 64-bit).

**Comment by boofish** [comment]
Thanks for your prompt reply!

Currently, I have used Ubuntu 18.04, which may be inappropriate. 
l download the source code of llvm and musl from the project `DataShield`,
but the compiler (`clang`  ) to compile the project  is a default configuration, 
the `clang` version is `9.0.1`.

Could you please give me more detailed information about the environment configuration, 
such as the compiler version, the musl version, etc.?

**Comment by boofish** [comment]
Great!
Thank you very much! I have succeeded in running the binaries.

In order to help those who are also interested in reproducing this project, 
I share some details as follows:

1. A totally new ubuntu 16.04 LTS
2. Install `clang-3.9`, `ninja-build`,  `cmake`,  `binutils-dev`
3. Configure the compiler: ` ln -s clang clang-3.9` and `ln -s clang++ clang++-3.9`
4. Follow the steps in `readme`

It is wonderful!

**Comment by gannimo** [comment]
Awesome, happy to hear that it worked out when using older versions of the software.
I've also added a comment to the README after your confirmation.
